# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6fd04d2b7266b1c12b452e7642c72e150c4c03f7b66485c9cb540057f95d806a06dfcb7bc3cf8d999bd9df5b1c7b3aa14e5b8bd224a0b01be8055a3adf509c

test:
  secret_key_base: d272d87859bbefbd072965c993f2646a8c548b88338f8e74cbd36791aa7e0d1cb8c11220102b3c6b00f6af9ed55d74d9f0d834777a2c007d14106338feaa1204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
