# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  consumer_key: 'xxxxxxxxxxx'
  consumer_secret: 'xxxxxxxxxxx'
  access_token: 'xxxxxxxxxxx'
  access_token_secret: 'xxxxxxxxxxx'

development:
  secret_key_base: xxxxxxxxxxxx
  <<: *default_twitter

test:
  secret_key_base: xxxxxxxxxxxx
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
